name: test suite
on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo fmt -- --check
      - run: cargo clippy --workspace -- -Dwarnings
