name: test suite
on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy, rustfmt
      - run: |
          sudo apt update
          sudo apt install -y --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - run: cargo fmt -- --check
      - run: cargo clippy --workspace -- -Dwarnings
